In [1]:
import numpy as np

# =========================
# A.1 Matrix Multiplication
# =========================

# 3x2 (teams x months)
Resources_Matrix = np.array([
    [100, 120],
    [80,  90],
    [150, 110]
])

# 2x2 (adjustment factors)
Allocation_Factors = np.array([
    [1.1, 0.9],
    [0.95, 1.05]
])

Result_Matrix = Resources_Matrix @ Allocation_Factors

print("A.1 Result (3x2 matrix):")
print(Result_Matrix)
print()


# =========================
# A.2 Element-wise Addition
# =========================

# 3 factories x 7 days
Shift_A_Production = np.array([
    [10, 12, 11, 13, 15, 14, 16],
    [20, 22, 19, 21, 23, 24, 25],
    [30, 28, 29, 31, 32, 33, 34]
])

Shift_B_Production = np.array([
    [8,  9,  7,  10, 11, 12, 13],
    [15, 14, 16, 17, 18, 19, 20],
    [25, 26, 24, 27, 28, 29, 30]
])

Total_Production = Shift_A_Production + Shift_B_Production

print("A.2 Total Production:")
print(Total_Production)
print()


# =========================
# A.3 Sigmoid Function
# =========================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

test_values = np.array([-2, -1, 0, 1, 2])
sigmoid_output = sigmoid(test_values)

print("A.3 Sigmoid Output:")
print(sigmoid_output)
print()


# =========================
# A.4 Sigmoid Gradient
# =========================

def sigmoid_gradient(x):
    s = sigmoid(x)
    return s * (1 - s)

gradient_output = sigmoid_gradient(test_values)

print("A.4 Sigmoid Gradient:")
print(gradient_output)


A.1 Result (3x2 matrix):
[[224.  216. ]
 [173.5 166.5]
 [269.5 250.5]]

A.2 Total Production:
[[18 21 18 23 26 26 29]
 [35 36 35 38 41 43 45]
 [55 54 53 58 60 62 64]]

A.3 Sigmoid Output:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]

A.4 Sigmoid Gradient:
[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
